import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "@/utils/api";
import LoggedLayout from "@/components/layout/private";
import EcheanceUpdate from "@/components/echeance/update";
import { useRouter } from "next/router";

const ModifEcheance = () => {
  const router = useRouter();

  const { data: echeance, status } = api.echeance.findById.useQuery({
    id: router.query.id as string,
  });

  return (
    <>
      <Head>
        <title>Deadline - Modifier echeance</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoggedLayout>
        <div className="flex min-h-screen flex-col content-center items-center justify-center ">
          <div className="container hidden sm:flex sm:flex-row">
            {status === "loading" ? (
              <div className="mt-6 flex items-center justify-center">
                <div className="h-10 w-10 animate-spin rounded-full border-pink-600"></div>
              </div>
            ) : (
              <EcheanceUpdate echeance={echeance} title="Modifier échéance" />
            )}
          </div>
        </div>
      </LoggedLayout>
    </>
  );
};

export default ModifEcheance;
