import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "@/utils/api";
import LoggedLayout from "@/components/layout/private";
import EcheanceCreate from "@/components/echeance/create";

const NouvelleEcheance = () => {
  return (
    <>
      <Head>
        <title>Deadline - Nouvelle echeance</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoggedLayout>
        <div className="flex min-h-screen flex-col content-center items-center justify-center ">
          <div className="container hidden sm:flex sm:flex-row">
            <EcheanceCreate title="Nouvelle échéance" />
          </div>
        </div>
      </LoggedLayout>
    </>
  );
};

export default NouvelleEcheance;
