import Head from "next/head";
// import { signIn, signOut, useSession } from "next-auth/react";

// import { api } from "@/utils/api";
import { Button, Card } from "@/components/core";
import LoggedLayout from "@/components/layout/template";
import TableDashboard from "@/components/dashboard/tabledashboard";
import { type Echeance } from "@/utils/models";
import { GetServerSideProps } from "next";
import { trpc } from "@/utils/api";

interface HomeProps {
  echeances: Echeance[];
}

const Home = ({ echeances }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Deadline</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoggedLayout>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Card>
            <div className="container flex flex-col">
              <div className="flex items-center gap-4">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6 text-pink-600 sm:h-8 sm:w-8"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M13 10V3L4 14h7v7l9-11h-7z"
                  />
                </svg>

                <h3 className="text-xl font-bold sm:text-2xl">Dashboard</h3>
                <div className="grow" />
                <Button rounded>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke-width="1.5"
                    stroke="currentColor"
                    className="h-6 w-6"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <span className="text-md font-bold sm:text-sm">Tache</span>
                </Button>
              </div>
              <Card className="mt-4">
                <div className="container flex flex-col">
                  <h5 className="text-md sm:text-lg">Liste des taches</h5>
                  <TableDashboard className="mt-2" data={echeances} />
                </div>
              </Card>
            </div>
          </Card>
        </div>
      </LoggedLayout>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<{
  echeances: Echeance[];
}> = async () => {

  const echecancesQuery = await trpc.example.



  return { props: { echeances: [] } };
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
